### ISSUE TITLE
Deref/DerefMut rather than setters?

### ISSUE THREAD

**Issue by Christopher22** [rust-av/ffms2-rs#16]
Hey @Luni-4, 
thank you for the marvelous crate! 

I've got one design question: What is the aim of the setter functions, generated with the `set_params!` macro? If we would implement Deref and DerefMut targeting the underlying struct of `$param`, we might get a "more rusty" interface for free...

At least for the Video struct, that might be the only way to access the private properties. I'm happy to implement this.

**Comment by Luni-4** [comment]
Hey @Christopher22, nice to meet you! :smile: 

You're completely right, that would be a better design. I wrote `ffms2-rs` some time ago when I had started writing code in `Rust`. So feel free to add `Deref` and `DerefMut` and clean up the rest of the code also. Thanks for the help!

Can I assign this issue to you?

**Comment by Christopher22** [comment]
Sure! :)

**Comment by Luni-4** [comment]
Closed for #19
