### ISSUE TITLE
Outdated ffms2-sys on crates.io

### ISSUE THREAD

**Issue by Christopher22** [rust-av/ffms2-rs#21]
The version of ffms2-sys on crates.io (0.1.0) is outdated. Uploading the new version allow us to keep both parts in sync during development. Additionally, the subsequent increase of the version in ffms2-rs finally allow its compilation on Windows not possible by now.

**Comment by Luni-4** [comment]
Blocked by https://github.com/rust-av/ffms2-rs/blob/master/src/utility.rs#L22

I prefer not having dead code around, so up till we don't fix that problem, I'm not going to release

**Comment by Luni-4** [comment]
Just released on `crates.io`, thanks again for your help @Christopher22! :smile:
